-- First, delete all existing records from product_event_definitions
DELETE FROM product_event_definitions;

-- Now insert all the new records from the Excel file
INSERT INTO product_event_definitions (module_code, product_code, product_name, event_code, event_name) VALUES
('TF', 'ILC', 'Import Letter of Credit', 'CAN', 'Cancellation'),
('TF', 'ODC', 'Outward Documentary Collection Bills', 'UPD', 'Update Bill'),
('TF', 'SHG', 'Shipping Guarantee', 'LNK', 'Link/Delink'),
('TF', 'ILC', 'Import Letter of Credit', 'ISS', 'Issuance'),
('TF', 'ILC', 'Import Letter of Credit', 'AMD', 'Amendment'),
('TF', 'REM', 'Remittance', 'PIO', 'Process Inward/Outward Remittance'),
('TF', 'ELB', 'Bills Under LC (Export Bills / Negotiation Bills)', 'RES', 'Resolve Discrepancies'),
('TF', 'TRL', 'Trade Loan', 'WRF', 'Write-off'),
('TF', 'OSB', 'Outward Standby Letter of Credit', 'ISS', 'Issuance'),
('TF', 'IDC', 'Inward Documentary Collection Bills', 'SET', 'Process Settlement'),
('TF', 'ELB', 'Bills Under LC (Export Bills / Negotiation Bills)', 'BLG', 'Lodgement'),
('TF', 'ODC', 'Outward Documentary Collection Bills', 'SET', 'Process Settlement'),
('TF', 'ELB', 'Bills Under LC (Export Bills / Negotiation Bills)', 'SET', 'Negotiation / Purchase / Discounting'),
('TF', 'OSB', 'Outward Standby Letter of Credit', 'CAN', 'Cancellation'),
('TF', 'OBG', 'Outward Bank Guarantee', 'CAN', 'Cancellation'),
('TF', 'ELC', 'Export Letter of Credit', 'REV', 'Review Pre-Advised LC'),
('TF', 'OSB', 'Outward Standby Letter of Credit', 'CLM', 'Claim'),
('TF', 'IBG', 'Inward Bank Guarantee', 'RAC', 'Record Amendment Consent'),
('TF', 'ISB', 'Inward Standby Letter of Credit', 'RAC', 'Record Amendment Consent'),
('TF', 'TRL', 'Trade Loan', 'CRE', 'Create Loan'),
('TF', 'OSB', 'Outward Standby Letter of Credit', 'CLS', 'Close'),
('TF', 'ISB', 'Inward Standby Letter of Credit', 'CLM', 'Claim'),
('TF', 'OBG', 'Outward Bank Guarantee', 'AMD', 'Amendment'),
('TF', 'ILC', 'Import Letter of Credit', 'EXP', 'Expiry'),
('TF', 'IBG', 'Inward Bank Guarantee', 'ADV', 'Advise'),
('TF', 'OBG', 'Outward Bank Guarantee', 'CNF', 'Confirmation'),
('TF', 'ISB', 'Inward Standby Letter of Credit', 'ADV', 'Advise'),
('TF', 'ELC', 'Export Letter of Credit', 'CNF', 'Confirmation'),
('TF', 'SHG', 'Shipping Guarantee', 'ISS', 'Issuance'),
('TF', 'ODC', 'Outward Documentary Collection Bills', 'BLG', 'Bill Lodgement'),
('TF', 'ISB', 'Inward Standby Letter of Credit', 'CAN', 'Cancellation'),
('TF', 'SHG', 'Shipping Guarantee', 'CAN', 'Cancellation'),
('TF', 'IBG', 'Inward Bank Guarantee', 'AMD', 'Amendment'),
('TF', 'ISB', 'Inward Standby Letter of Credit', 'AMD', 'Amendment'),
('TF', 'ILB', 'Bills Under Import LC', 'UPD', 'Update Bill'),
('TF', 'IBG', 'Inward Bank Guarantee', 'CLM', 'Claim'),
('TF', 'ELC', 'Export Letter of Credit', 'RAC', 'Record Amendment Consent'),
('TF', 'ELC', 'Export Letter of Credit', 'TRF', 'Transfer'),
('TF', 'OBG', 'Outward Bank Guarantee', 'CLS', 'Close'),
('TF', 'ELC', 'Export Letter of Credit', 'ASN', 'Assignment'),
('TF', 'TRL', 'Trade Loan', 'TRF', 'Transfer Loan'),
('TF', 'TRL', 'Trade Loan', 'UPD', 'Update Loan'),
('TF', 'REM', 'Remittance', 'RET', 'Return / Reject'),
('TF', 'OBG', 'Outward Bank Guarantee', 'ISS', 'Issuance'),
('TF', 'SHG', 'Shipping Guarantee', 'AMD', 'Amendment'),
('TF', 'ELC', 'Export Letter of Credit', 'ADV', 'Advise'),
('TF', 'OSB', 'Outward Standby Letter of Credit', 'AMD', 'Amendment'),
('TF', 'OSB', 'Outward Standby Letter of Credit', 'CNF', 'Confirmation'),
('TF', 'IDC', 'Inward Documentary Collection Bills', 'ACC/REF', 'Acceptance/Refusal'),
('TF', 'IDC', 'Inward Documentary Collection Bills', 'BLR', 'Document/Bill Receipt'),
('TF', 'ILB', 'Bills Under Import LC', 'SET', 'Process Bill Settlement'),
('TF', 'SHG', 'Shipping Guarantee', 'CLM', 'Claim / Discharge'),
('TF', 'IBG', 'Inward Bank Guarantee', 'CAN', 'Cancellation'),
('TF', 'TRL', 'Trade Loan', 'SET', 'Repayment'),
('TF', 'ILB', 'Bills Under Import LC', 'ACC/REF', 'Acceptance / Refusal'),
('TF', 'OBG', 'Outward Bank Guarantee', 'CLM', 'Claim'),
('TF', 'ILB', 'Bills Under Import LC', 'BLG', 'Bill Lodgement');