-- Insert dummy bill data for testing Finance/Discount functionality
INSERT INTO public.outward_documentary_collection_bills (
  user_id,
  bill_reference,
  bill_amount,
  bill_currency,
  drawer_name,
  drawer_address,
  drawee_payer_name,
  drawee_payer_address,
  collecting_bank,
  collecting_bank_address,
  collecting_bank_swift_code,
  tenor_days,
  documents_against,
  presentation_instructions,
  interest_charges,
  protect_charges,
  special_instructions,
  status,
  created_at,
  updated_at
) VALUES 
(
  '8cceba0f-c1a9-4074-8dbc-be256e0cc448',
  'ODCBILL1',
  150000.00,
  'USD',
  'ABC Export Company Ltd',
  '123 Business District, New York, NY 10001, USA',
  'XYZ Import Corporation',
  '456 Industrial Area, Mumbai, MH 400001, India',
  'HDFC Bank Ltd',
  'Trade Finance Branch, Mumbai, India',
  'HDFCINBB',
  90,
  'payment',
  'D/P',
  'waive',
  'collect',
  'Please contact drawer before acceptance',
  'submitted',
  NOW(),
  NOW()
),
(
  '8cceba0f-c1a9-4074-8dbc-be256e0cc448',
  'BILL2',
  75000.00,
  'EUR',
  'European Exports GmbH',
  '789 Commercial St, Frankfurt, Germany',
  'Asian Imports Pte Ltd',
  '321 Trade Center, Singapore 018989',
  'DBS Bank Ltd',
  'Corporate Banking, Singapore',
  'DBSSSGSG',
  60,
  'acceptance',
  'D/A',
  'collect',
  'collect',
  'Documents to be released against acceptance only',
  'submitted',
  NOW() - INTERVAL '5 days',
  NOW() - INTERVAL '5 days'
),
(
  '8cceba0f-c1a9-4074-8dbc-be256e0cc448',
  'BILL3',
  220000.00,
  'GBP',
  'British Trading Co Ltd',
  '456 London Bridge, London, UK',
  'Middle East Trading LLC',
  '789 Business Bay, Dubai, UAE',
  'Emirates NBD Bank',
  'International Trade Finance, Dubai',
  'EBILAEAD',
  120,
  'payment',
  'D/P',
  'waive',
  'account to bank',
  'Special handling required for perishable goods documents',
  'submitted',
  NOW() - INTERVAL '10 days',
  NOW() - INTERVAL '10 days'
),
(
  '8cceba0f-c1a9-4074-8dbc-be256e0cc448',
  'ODCBILL4',
  95000.00,
  'USD',
  'Global Exporters Inc',
  '999 Export Plaza, Los Angeles, CA 90001, USA',
  'Pacific Importers Ltd',
  '888 Harbor View, Tokyo, Japan',
  'Mizuho Bank Ltd',
  'International Division, Tokyo',
  'MHCBJPJT',
  45,
  'acceptance',
  'D/A',
  'collect',
  'collect',
  'Documents include commercial invoice, packing list, and B/L',
  'submitted',
  NOW() - INTERVAL '2 days',
  NOW() - INTERVAL '2 days'
),
(
  '8cceba0f-c1a9-4074-8dbc-be256e0cc448',
  'BILL5',
  180000.00,
  'AUD',
  'Australian Commodities Pty',
  '555 Collins Street, Melbourne, Australia',
  'Canadian Imports Corp',
  '777 Bay Street, Toronto, ON, Canada',
  'Royal Bank of Canada',
  'Trade Finance Division, Toronto',
  'ROYCCAT2',
  75,
  'payment',
  'D/P',
  'waive',
  'collect',
  'Freight prepaid, documents available for collection',
  'submitted',
  NOW() - INTERVAL '7 days',
  NOW() - INTERVAL '7 days'
);