// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://txkejzwremnrpyksizso.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR4a2VqendyZW1ucnB5a3NpenNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1NzAwNzgsImV4cCI6MjA2NTE0NjA3OH0.EVHMInbqcv3erCkX-WwylnmLOpQZwVH6Ga854q6Fyfc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});